function formatEstablishmentDataIntoInsertableFormat(data) {
  // Missing, description data...
  // Require longitude and latitude with Google Geocode API - Research later
  let addressArray = data.address.split(",");
  return {
    name: data.name,
    city: addressArray[1],
    address_line: addressArray[0],
    province: addressArray[2],
    postal_code: addressArray[3],
    description: "",
    latitude: "",
    longitude: "",
  }
}

// function formatHappyHrDataIntoInsertableFormat(data) {
  
// }

function formatMenuItemIntoNameAndPrice(itemData) {
  let regex = new RegExp(/+\s-\s\$\d+/, 'gi');
}

let singleData = { name:'131 Water',
  drinks:'Monday - Sunday 3 PM - 6 PM & 10 PM - Close Discounted Beer & Wine, Highballs', 
  food:`Monday - Sunday 3 PM - 6 PM & 9 PM - 
    1 AM Bloomin Poutine - $8 
    Korean Fried Chicken - $7.50 
    Thai Chili Tofu - $5 
    Poutine - $7 
    Salt Pepper Dry Ribs - $7 
    Blooming Onion - $5 
    Yam Fries - $4 
    Basket of Fries - $4 
    Edamame - $6.50 
    Deep Fried Pickles - $7.50 
    Chicken Tenders - $6.50 
    Hummus & CHips - $4.50 
    New York Cheese Cake - $5 
    Warm Toffee Pudding - $5`, 
  address:'131 Water St, Vancouver, BC, V6B 4M3', 
  phone:'604-669-7219', 
  url:'https://www.arcdining.com/' };

formatEstablishmentDataIntoInsertableFormat(singleData);

let allData = [
  { name:'La Mezcaleria Gastown', 
  drinks:'Tuesday - Thursday 5 PM - 6 PM Friday - Sunday 2 PM - 5 PM House Wines (5oz) - $6 Juan de Fuca Lager (12oz can) - $6 Palomita (1.5oz) - $7 Juan de Fuca Michelada (12oz) - $7', food:'Tuesday - Thursday 5 PM - 6 PM Friday - Sunday 2 PM - 5 PM Ceviche Callejero - $6 Amigos Flight - $16 Quesito Fundido - $8', address:'68 E Cordova St, Vancouver, BC V6A 1K2', phone:'778-379-6447', url:'http://laterrazza.ca/#findus' }, { name:'La Pentola', 
  drinks:'Monday - Sunday 9 PM - Close Negroni - $6 Red and White Wine - $5 Local Draft Beer - $4', food:'Monday - Sunday 9 PM - Close Olives & Pecorino Cheese - $5 Ricotta on Toast - $5 Baccala on Toast - $5 Grilled Prawns - $5 Meatballs in Tomato Sauce - $5', address:'350 Davie St, Vancouver, BC, V6B 5Z6', phone:'604-642-0557', url:'http://www.lasmargaritas.com/#section-2194' }, { name:'La Terrazza', 
  drinks:'Monday - Sunday 5 PM - 7 PM Old Fashioned Cocktail - $8 Glass Of House Red Or White Wine - $6 Glass Of Premium Wine - $10 Chardonnay Marrenon (unoaked, France) 2014 - $45 Chianti, Terre Di Poppiano (italy) 2014 - $45 Highballs - $5 Draft Beer - $5', food:'Monday - Sunday 5 PM - 7 PM Calamari Fritti - $10.88 Carpaccio - $10.88 Salumi - $10.88 Strozzapreti Bolognese - $10.88 Gnocchi Al Forno - $10.88 Giardiniera - $10.88 Buffalo Bison Sliders - $10.88 Schiacciata - $10.88 Prawn Cocktail - $10.88', address:'1088 Cambie St, Vancouver, BC, V6B 6J5', phone:'604-899-4449', url:'http://donnellygroup.ca/library-square/' }, { name:'Las Magaritas', 
  drinks:'Monday - Thursday 2:30 PM - 5:30 PM La Perla Pilsner (12oz) - $4 Highballs - $4 Slushy Margarita (1 Oz) - $5 Lagunitas Ipa (12oz) - $5 La Perla Pilsner (16oz) - 5 House Wine (6oz) - $6 Classic Margarita (on The Rocks) - $6 Sangria (red Or White) - $6', food:'Monday - Thursday 2:30 PM - 5:30 PM Chipotle Fries - $5 Mini Chimis - $5 Taquitos - $7 Mexican Poutine - $7 3 Veggie Street Tacos - $7 Nachos Locos (1⁄2) - $7 Ground Beef Hardshell Tacos (2) - $12 Chicken Chimichanga - $12 Beef Burrito - $12', address:'1999 W 4th Ave, Vancouver, BC, V6J 1M7', phone:'604-734-7117', url:'http://liftbarandgrill.com/' }, { name:'Library Square', 
  drinks:'', food:'Monday - Friday 3 PM - 6 PM Charred Shishito Peppers - $6 Crisp Cauliflower - $13 Red Chili Wings - $14 Buttermilk Chicken - $12 Yam Chips - $8 Fish Tacos - $14 Fries - $7 Seasonal Soup - $9', address:'300 W Georgia St, Vancouver, BC, V6B 6B4', phone:'604-633-9644', url:'https://locusonmain.com/' }, { name:'LIFT Bar Grill View', 
  drinks:'Monday - Sunday 3 PM - 6 PM Rose, White Or Red House Wine - $5 Red Truck Lager - $5 Parkside Pale Ale - $5 Well Drinks $ 5', food:'Monday - Sunday 3 PM - 6 PM Assorted Olives - $4 French Fries - $6 Humboldt Squid - $9 Maui Beef Rib - $12 Tempura Prawns - $10 Halibut & Chips - $16 Lobster Mac and Cheese - $13 Sweet & Spicy Chicken Karaage - $8 Creamed Spinach & Salmon Gravlax - $8 Vegan Roll - $7 Spicy Tuna Roll - $10 Salmon Aburi Roll - $10', address:'333 Menchion Mews, Vancouver, BC V6G 3H2', phone:'604-689-5438', url:'http://malones.bc.ca/' }, { name:'Locus On Main', 
  drinks:'Monday - Sunday 3 PM - 6 PM All draught beer - $4 House wines - $5 Caesars & blackberry lemonades - $5 Monday - Sunday 10 PM - Close All draught beer - $4 House wines - $5 Nightly 2 oz. cocktail feature - $6', food:'Monday - Sunday 3 PM - 6 PM Sunday - Thursday 10 PM - Close 25% off all appetizers', address:'4121 Main St, Vancouver, BC, V5V 3P6', phone:'604-708-4121', url:'http://mamietaylors.ca/' }, { name:'Malone’s Social Lounge & Taphouse', 
  drinks:'Monday - Sunday 3 PM - 6 PM Saturday 3 PM - 6 PM & 9 PM - 11 PM All Draft Beer - $2 Off Highballs (1oz) - $3.90 House Wine (6oz) - $6 House Wine (9oz) - $9', food:'', address:'608 W Pender St, Vancouver, BC, V6B 1V8', phone:'604-684-9977', url:'http://marketkitchen.com/market_by_jean_georges_vancouver/' }, { name:'Mamie Taylor’s', 
  drinks:'Monday - Friday 5 PM - 6 PM Saturday & Sunday 3 PM - 5 PM Can Of Parkside ‘Dawn’ Pilsner -$ 4.50 Draft Beer - $5 Glass Of Wine -$6 Mamie Taylor Cocktail - $7', food:'Monday - Friday 5 PM - 6 PM Saturday & Sunday 3 PM - 5 PM Ham Grenades (3 pieces) - $4 Meatballs (3 pieces) - $4 Chicken Wings (3 pieces) -$5 Sliders (2 pieces) - $5', address:'251 E Georgia St, Vancouver, BC, V6A 1Z6', phone:'604-620-8818', url:'http://www.martinis.ca/' }, { name:'Market by Jean-Georges', 
  drinks:'Monday - Sunday 3 PM - 6 PM Orchard Harvest - $10 Ru & Rye - $10 Purple Tree - $5 Red and White Wine - $7 Red Truck Lager - $5 Red Racer Pale Ale - $5', food:'Monday - Sunday 3 PM - 6 PM House-Cut Kennebec Frites - $8 Truffle Fries - $9 Grilled Cheese Minis - $9 West Coast Seafood Okonomiyaki - $12 Korean Fried Chicken - $10 Market Pizza - $12', address:'1115 Alberni St, Vancouver, BC, V6E 0A8', phone:'604-695-1115', url:'http://nightingalempls.com/' }, { name:'Martini’s Restaurant', 
  drinks:'Monday - Sunday 3 PM - 6 PM Friday & Saturday 11 PM - 1:30 AM Bottled Steamwhistle Pilsner - $3.50 Seasonal Tap (11oz glass) - $3 Jamesons (1oz) - $3 House Red, White (6oz) - $4', food:'Monday - Sunday 3 PM - 6 PM Friday & Saturday 11 PM - 1:30 AM Garlic Cheese Bread - $2.25 Homous or Tzatziki With Pita - $4.50 Prawn Skewer - $4.50 Pulled Pork Tacos - $4.50 Chicken Wings (All Kinds) - $7 BBQ Ribs - $7', address:'151 W Broadway, Vancouver, BC, V5Y 1P4', phone:'604-873-0021', url:'http://nomad-vancouver.ca/contact/' }, { name:'Nightingdale', 
  drinks:'Monday - Friday 4 PM - 6 PM & 11 PM - 1 AM Rail Drinks - $3.50 Cocktail - $5 Select Taps - $3.5 Hamm\'s - $2.5 Grain Belt Premium Tall Boy - $2.75 PBR Tall Boy - $2.75 Glass of House Red - $5 Bottle of House Red - $20 Glass of House White - $5 Bottle of House White - $20 Glass of House Sparkling - $5 Bottle of House Sparkling - $20', food:'Saturday - Sunday 2:30 PM - 4 PM & 11 PM - 1 AM Oysters - $2.5 French Fries w/ Malt Vinegar Aioli - $4 Seasonal Bruschetta - $6 Smoked Chicken Liver Pate w/ Bacon Marmalade - $8 Chicken Wings - $8 Pickle Plate - $8 Fish Plate - $10 Meat Plate - $12 Cheese Plate - $10 Nightingale Burger (Dine in, early Happy Hour only) - $10 *Add a Hamms to your burger - $1', address:'1017 W Hastings St, Vancouver, BC, V6E 0C4', phone:'604-695-9500', url:'http://www.notch8-dining.com/' }, { name:'Nomad', 
  drinks:'Monday - Friday 5 PM - 6 PM & 10 PM - Close Saturday - Sunday 2 PM - 6 PM & 10 PM - Close Beer - $5 Cider - $5.50 Negroni - $6 Femme Fatale - $6 House White or Red Wine - $1/oz Rose - $6', food:'Monday - Friday 10 PM - Close Saturday - Sunday 2:30 PM - 5 PM & 10 PM - Close Black Garlic Popcorn - $5 Warm Olives - $6 House-Made Sourdough Bread - $5 Kennebec Potato Fries - $8 Organic Sunchoke “Wings” - $14 Cured Arctic Char - $17 Humboldt Squid - $14 Crispy Polenta Fritters - $8 Korean BBQ Pork Belly on Ciabatta - $16 Chef’s Feature Soup - $10', address:'3950 Main St, Vancouver, BC, V5V 3P2', phone:'604-708-8525', url:'https://www.nuba.ca/' }, { name:'Notch8 Restaurant & Bar', 
  drinks:'Monday - Friday 3 PM - 6 PM $8 - Mission Hill Chardonnay - Mission Hill Cabernet Merlot - Red Truck Lager', food:'Monday - Friday 3 PM - 6 PM $8 - Fried Herb Tossed Pork Ribs - Fritto Misto - Yorkshire Pudding Prime Rib Bites - Oysters On The Half Shell - Fried Pickles', address:'900 W Georgia St, Vancouver, BC, V6C 2W6', phone:'604-662-1900', url:'https://www.nuba.ca/' }, { name:'Nuba Gastown', 
  drinks:'Monday - Sunday 3 PM - 5 PM Happy Hour specials on beer, wine, and cocktails vary by location', food:'Monday - Sunday 3 PM - 5 PM $8 - Najib’s Special - Garden Falafel - Lamb Hushwie - Mjadra - Chicken Shish Tawook - Vegan Stew $7 - Hummus - Baba Ghanooj - Mama Dallou’ah - Taboulleh Salad $3 - Marinated Olives - Macedonian Feta', address:'207 W Hastings St, Vancouver, BC, V6B 1K6', phone:'604-688-1655', url:'https://www.nuba.ca/' }, { name:'Nuba Kitsilano', 
  drinks:'Monday - Sunday 3 PM - 5 PM Happy Hour specials on beer, wine, and cocktails vary by location', food:'Monday - Sunday 3 PM - 5 PM $8 - Najib’s Special - Garden Falafel - Lamb Hushwie - Mjadra - Chicken Shish Tawook - Vegan Stew $7 - Hummus - Baba Ghanooj - Mama Dallou’ah - Taboulleh Salad $3 - Marinated Olives - Macedonian Feta', address:'3116 W Broadway, Vancouver, BC, V6K 2G9', phone:'604-336-1797', url:'https://www.nuba.ca/' }, { name:'Nuba Mt Pleasant', 
  drinks:'Monday - Sunday 3 PM - 5 PM Happy Hour specials on beer, wine, and cocktails vary by location', food:'Monday - Sunday 3 PM - 5 PM $8 - Najib’s Special - Garden Falafel - Lamb Hushwie - Mjadra - Chicken Shish Tawook - Vegan Stew $7 - Hummus - Baba Ghanooj - Mama Dallou’ah - Taboulleh Salad $3 - Marinated Olives - Macedonian Feta', address:'146 E 3rd Ave, Vancouver, BC, V5T 1C8', phone:'604-568-6727', url:'http://www.persesocialcorner.com/' }, { name:'Nuba Yaletown', 
  drinks:'Monday - Sunday 3 PM - 6 PM Happy Hour specials on beer, wine, and cocktails vary by location', food:'Monday - Sunday 3 PM - 6 PM $8 - Najib’s Special - Garden Falafel - Lamb Hushwie - Mjadra - Chicken Shish Tawook - Vegan Stew $7 - Hummus - Baba Ghanooj - Mama Dallou’ah - Taboulleh Salad $3 - Marinated Olives - Macedonian Feta', address:'508 Davie St, Vancouver, BC, V6B 3N9', phone:'604-661-4129', url:'http://www.pidginvancouver.com/' }, { name:'per se Social Corner', 
  drinks:'Monday - Friday 3 PM - 5:30 PM Well Highballs (1oz) - $5 | (2oz) $7 - Stoli Vodka, Bombay gin, Bacardi rum, Canadian Club whisky Beer on Tap (Rosalinda Lager) - $3.50 White wine (Pinot Grigio) - $5 Red Wine (Valpolicella) - $5 Whiskey (Jameson Irish whiskey) - $5 Cider (Turning Point cider on draught) - $4', food:'Monday - Friday 3 PM - 5:30 PM $5 - Hummus - Pinche Chips - Arancini Di Palermo - Charred Chorizo - Diavola Formaggi - Pane Parmigiano $5 Off All Pizze See Pizze menu for selection', address:'891 Homer St, Vancouver, BC, V6B 2W2', phone:'604-428-6111', url:'http://thaihouse.com/pink-elephant-thai/' }, { name:'Pidgin Restaurant', 
  drinks:'Monday - Sunday 5 PM - 6 PM Cocktails $8.75 Sbagliato Penicillin The Brooklyn El Presidente Moscow Mule Pidgin Collins Tommy\'s Margarita Wine - $7.50 Tiger Tall Can - $5', food:'Monday - Sunday 5 PM - 6 PM Daily Food Specials', address:'350 Carrall St, Vancouver, BC, V6B-2J3', phone:'604-620-9400', url:'https://www.pizzeriafarina.com/' }, { name:'Pink Elephant Thai', 
  drinks:'Monday - Sunday 3:30 PM - 5:30 PM $4 - White Wine (4 oz) - Rose (4 oz) - Red Wine (4 oz) $5 - Singha Beer (330ml) - House High Balls (1oz)', food:'Monday - Sunday 3:30 PM - 5:30 PM $5 - Shrimp Cakes 2pcs - Fish Cakes 5pcs - Crispy Wonton 5pcs $7 - Vegetarian Spring Rolls 4pcs - Calamari - Wings (Red curry or Chili Basil) - Chicken Satay $9 Signature Salads - Lettuce Wrap - Yum Neau - Som Tum - Larb Gai', address:'1152 Alberni St, Vancouver, BC, V6E 1V8', phone:'604-646-8899', url:'http://www.portlandcraft.com/' }, { name:'Pizza Farina', 
  drinks:'Monday - Sunday 5 PM - 6 PM Margherita Pizza & Good Company Lager - $15', food:'', address:'915 Main St, Vancouver, BC, V6A 2V8', phone:'604-681-9334', url:'https://www.pourhousevancouver.com/' }, { name:'Portland Craft', 
  drinks:'Monday - Sunday 3 PM - 5 PM & 2 Hours Before Close Select Us Craft Beer - $5.75 Local Draft Beer (14oz) - $4 Local Draft Beer (20oz) - $5 House Red & White Wine - $5.50 Single Highballs - $4.5 Double Highballs - $7 Jameson - $4.50', food:'Monday - Sunday 3 PM - 5 PM Old Bay Spiced Popcorn - $3 Fries With Dip - $5 Poutine - $10 Salt & Pepper Wings - $10 Meat Pizza - $11.50 Veggie Pizza - $11.50 Portland Craft Burger - $12.50 Mac & Cheese - $11.50 Korean BBQ Veggie Wrap - $11.50 Blackened COD Burger - $15', address:'3835 Main St, Vancouver, BC, V5V 3P1', phone:'604-569-2494', url:'http://www.relishthepub.com/relish/' }, { name:'Pourhouse', 
  drinks:'Monday - Sunday 5 PM - 6 PM & 11 PM - Close Draught Beer - $6 Aperol Spritz - $8 Cynar Spritz - $8 Select Red and White Wine - $8', food:'Monday - Sunday 5 PM - 6 PM & 11 PM - Close IPA Beer nuts - $4 Warm Olives - $6 Squash Hummus - $7 Scotch Egg - $7 Devils on Horseback - $6 Poutine - $6 Pourhouse Burger - $15 Veggie Burger - $12 Spaghetti & Meatballs - $15', address:'162 Water St, Vancouver, BC, V6B 1B2', phone:'604-568-7022', url:'http://www.revelroom.ca/' }, { name:'Relish', 
  drinks:'Drink Specials Monday - Sunday 2 PM - 6 PM $3 - Red Truck Lager (12oz) - Ale Draught Beer (12oz) House Wine (5oz) - $5 Single HighBalls - $4', food:'Monday - Sunday 2 PM - 6 PM Food Features - $5', address:'888 Nelson St, Vancouver, BC, V6Z 2S1', phone:'604-669-1962', url:'http://www.roguewetbar.com/broadway' }, { name:'Revel Room', 
  drinks:'Monday - Sunday 4 PM - 6 PM $5 - Red Truck Lager/Seasonal (20oz) - Parkside Dawn Pilsner (20oz) $6 Strange Fellows Talisman Pale Ale (20oz) Drfitwood Fat Tug (20oz) Rotating Taps (20oz) $7 - Red & White Wines (6oz) - Boston Whisky Sour - New York Whisky Sour $10 - Red & White Wines (9oz) - Classic Daiquri - Avivation - Cadillac Margarita', food:'Monday - Sunday 4 PM - 6 PM $7 - Crispy Fried Chicken Bites - Chicken & Andouile Gumbo Cup - New Orleans Style Pork Boudin Balls - Crab Cakes - Handcut French Fries - Cheeseburger Slider Duo', address:'238 Abbott St, Vancouver, BC, V6B 2K8', phone:'604-687-4088', url:'https://roguewetbar.com/convention-centre-lunch-pre-orders/' }, { name:'Rogue Kitchen & Wetbar Broadway', 
  drinks:'Monday - Sunday 3 PM - 6 PM All 60z Wines by the Glass - $2 OFF Fishbowls - $2 OFF Vancouver Craft Mules - $2 OFF Negronis - $2 OFF Highballs - $4 Doubles - $7 BC Session Ale 10oz - $3.70 BC Session Ale 18oz - $5.50 All Tequila - 30% OFF Don Julio Flights - $16 Buckets of Steamworks King Cans - $13.99 German Tap Rotator - $1 OFF Paper Plane - $2 OFF Aperol Spritz - $2 OFF', food:'Monday - Sunday 3 PM - 6 PM Dip Trio - $8.99 Ahi Tuna Cups - $3.49 Charcuterie Plate - $13.99 Dry Ribs - $7.99 Margherita Flatbread - $9.99 Cauliflower Veggie - $5.49 Jerk Chicken Taco - $5.49 Fish Taco - $5.49 Pork Belly Taco - $5.49 Korean Chicken Taco - $5.49 Steak taco - 5.49', address:'602 W Broadway, Vancouver, BC, V5Z 1G2', phone:'604-568-9400', url:'https://romersburgerbar.com/contact-locations/' }, { name:'Rogue Kitchen & Wetbar Burrard', 
  drinks:'Monday - Sunday 3 PM - 6 PM All 60z Wines by the Glass - $2 OFF Fishbowls - $2 OFF Vancouver Craft Mules - $2 OFF Negronis - $2 OFF Highballs - $4 Doubles - $7 BC Session Ale 10oz - $3.70 BC Session Ale 18oz - $5.50 All Tequila - 30% OFF Don Julio Flights - $16 Buckets of Steamworks King Cans - $13.99 German Tap Rotator - $1 OFF Paper Plane - $2 OFF Aperol Spritz - $2 OFF', food:'Monday - Sunday 3 PM - 6 PM Dip Trio - $8.99 Ahi Tuna Cups - $3.49 Charcuterie Plate - $13.99 Dry Ribs - $7.99 Margherita Flatbread - $9.99 Cauliflower Veggie - $5.49 Jerk Chicken Taco - $5.49 Fish Taco - $5.49 Pork Belly Taco - $5.49 Korean Chicken Taco - $5.49 Steak taco - 5.49', address:'200 Burrard Street, Vancouver, BC, V6C 3L6', phone:'604-428-2555', url:'https://roguewetbar.com/' }, { name:'Romer\’s Burger Bar Kitsilano', 
  drinks:'Monday - Sunday 3 PM - 6 PM & 9 PM - Close Daily Drink Deal - $5 Jameson Shots - $4 Craft Beer of the Day - $5 90z Romer\'s Sippin\' Red Or White Bc-vqa Wine - $7.50 Romer\'s Big Sippin\' Sangria Red, White or Rose - $7.75', food:'Monday - Sunday 3 PM - 6 PM & 9 PM - Close Buck a Bomb - $5 2 Romer\'s Sliders - $6.95 Fresh Chips And House-made Salsa - $5.95 Cheesy Spinach Kale Dip - (serves 2-3) - $9.95 Tuna Tataki Crisps - $8.95 Poutine - $6.95 Truffle Fries - (serves 2-3) - $6.95 Nachos Valentina - $9.95', address:'1873 W 4th Ave, Vancouver, BC, V6J 1M4', phone:'604-732-9545', url:'https://www.sharkclub.com/location/vancouver/' }, { name:'Rouge Kitchen & Wetbar', 
  drinks:'Monday - Sunday 3 PM - 6 PM All 60z Wines by the Glass - $2 OFF Fishbowls - $2 OFF Vancouver Craft Mules - $2 OFF Negronis - $2 OFF Highballs - $4 Doubles - $7 BC Session Ale 10oz - $3.70 BC Session Ale 18oz - $5.50 All Tequila - 30% OFF Don Julio Flights - $16 Buckets of Steamworks King Cans - $13.99 German Tap Rotator - $1 OFF Paper Plane - $2 OFF Aperol Spritz - $2 OFF', food:'Monday - Sunday 3 PM - 6 PM Dip Trio - $8.99 Ahi Tuna Cups - $3.49 Charcuterie Plate - $13.99 Dry Ribs - $7.99 Margherita Flatbread - $9.99 Cauliflower Veggie - $5.49 Jerk Chicken Taco - $5.49 Fish Taco - $5.49 Pork Belly Taco - $5.49 Korean Chicken Taco - $5.49 Steak taco - 5.49', address:'601 W Cordova St, Vancouver, BC, V6B 1G1', phone:'604-678-8000', url:'https://stregisbarandgrill.com/' }, { name:'Shark Club', 
  drinks:'Monday - Friday 3 PM - 6 PM & 6 PM - Close House Highballs (1oz) - $4.75 House Wine (5oz) - $4.75', food:'Monday - Friday 3 PM - 6 PM & 6 PM - Close $9 - Dirty chips - Parmesan tater tots - Meatball skillet - Queso Cheese & Bacon Dip', address:'180 W Georgia St, Vancouver, BC, V6B 4P4', phone:'604-687-4275', url:'http://www.steamworks.com/brew-pub' }, { name:'St Regis Bar & Grill', 
  drinks:'Monday - Sunday 2 PM - 6 PM & 8 PM - 10 PM Vodka, Gin, Rye, Rum (1oz) $4 | (2oz) $7 Jameson (1oz) - $5 House Lager (12oz) - $3.75 | (16oz) - $4.75 Stanley Park Amber Ale (12oz) - $3.75 | (16oz) - $5.25 Canadian (12oz) - $3.75 | (16oz) - $5 Guinness (12oz) - $4.50 | (16oz) - $7 Bomber Rotator (ask server for price) Wine O\'Clock Chardonnay (6oz) - $4.50 | (9oz) - $6.50 Wine O\'Clock Shiraz (6oz) - $4.50 | (9oz) - $6.50', food:'Monday - Sunday 2 PM - 6 PM & 8 PM - 10 PM Shrimp Gyoza - $7 Dry Ribs - $5 Fried Pickles - $5 Fry Trio - $8 Caesar Salad - $6 Ham & Pineapple Pizza - $10 Margherita Pizza - $10 Pepperoni Pizza - $10', address:'608 Dunsmuir St, Vancouver, BC, V6B 1Y6', phone:'604-696-5558', url:'http://tableaubarbistro.com/' }, { name:'Steamworks Brew Pub', 
  drinks:'Monday - Sunday Monday - Pitchers of beer - $3 off Tuesday - Tequila Cocktails - $2 off Wednesday - Craft Moscow Mules - $2 off Thursday - Beer Cocktails - $1 off Friday - Fishbowls - $2 off Saturday - Sangria - $1 off Sunday - Caesars - $2 off', food:'', address:'375 Water St, Vancouver, BC, V6B-1B8', phone:'604-689-2739', url:'https://www.tacofino.com/location/taco-bar' }, { name:'Tableau Bar Bistro', 
  drinks:'Monday - Sunday 2:30 PM - 5:30 PM & 9:30 PM - Close Highballs - $5 Bubbles - $6 House Wines (Red, White, Rosé) - $6 Blonde Bombshell Lager - $5 Feature beer- m/p Cocktail of the moment - m/p', food:'Monday - Sunday 2:30 PM - 5:30 PM & 9:30 PM - Close Seafood Tower serves 1 to 3 people - $50 West Coast Oysters ½ dozen - 15 dozen - $28 Gougéres - $9 Tableau Tarte Flambée - $9 Charcuterie Et Fromage selection of 4 - $20 Charcuterie Et Fromage selection of 6 - $24 Tableay Burger Et Frites - $12 Cocktail De Crevettes - $12 Le Petit Tartare - $10 Mushrooms on Toast - $10 Frites - $4 Frites Aux Truffes - $7 Escargots Bourgignons - $10', address:'1181 Melville St, Vancouver, BC, V6E 0A3', phone:'604-639-8692', url:'https://www.tacofino.com/location/taco-bar' }, { name:'Tacofino Gastown', 
  drinks:'Monday - Sunday 3 PM - 6 PM Margaritas - $8 All Draft Beer - $5 Wines by the Glass - $1 OFF', food:'Monday - Sunday 3 PM - 6 PM Chips & Dip- $10 Queso Fundido -$8 Spiced Mexican Corn Soup - $5 Wings -$6 Grilled Romaine Salad - $7 Nachos - $14 Tuna Aguachile - $10 Chicharrones - $8', address:'15 W Cordova St, Vancouver, BC, V6B 1C8', phone:'604-899-7907', url:'https://www.tacofino.com/location/yaletown-burrito-bar' }, { name:'Tacofino Taco Bar', 
  drinks:'Monday - Sunday 3 PM - 6 PM Margaritas - $8 All Draft Beer - $5 Wines By The Glass - $1 off', food:'Monday - Sunday 3 PM - 6 PM Chips & Dip - $10 Queso Fundido - $8 Spiced Corn Soup - $5 Wings - $6 Grilled Romaine Salad - $7 Nachos - $14 Tuna Aguachile - $10 Chicharrones - $8', address:'5 W Cordova St, Vancouver, BC, V6B 1C8', phone:'604-899-7907', url:'http://tapandbarrel.com/' }, { name:'Tacofino Yaletown', 
  drinks:'Monday - Sunday 3 PM - 6 PM Margaritas - $8 Glass Of Red Or White Wine - $5 Draft Beer - $5', food:'Monday - Sunday 3 PM - 6 PM Chips Salsa And Guac - $6 Nachos - $14 Grilled Romaine Salad - $6 Tater Tots (pm) - $5 Lamb Taquitos - $5', address:'1025 Mainland St, Vancouver, BC, V6B 5P9', phone:'778-379-8226', url:'https://www.tapandbarrel.com/' }, { name:'Tap & Barrel Convention Centre', 
  drinks:'Monday - Friday 2 PM - 6 PM Sunday - Thursday 2 PM - 6 PM & 9 PM - Close Well Highballs (1oz) - $4 Red Truck Lager (16oz) - $4.50 Red Truck Lager (20oz) - $6 BREWHALL Neon Lights Pale Ale (16oz0 - $5 BREWHALL Neon Lights Pale Ale (20oz) - $6.50 Rotating Cider (13oz) - $6 The Hatch Left Bank Blanc (6oz)- $6 The Hatch West Bank Rouge (6oz)- $6', food:'Monday - Friday 2 PM - 6 PM Sunday - Thursday 2 PM - 6 PM & 9 PM - Close Famous Fried Pickles - $6 Gyoza - $8 Handmade Guac & Salsa - $8 Hot Wings - $12 Soft Baked Pretzel - $5 Margherita Pizza - $12 Double Pepperoni Pizza - $12 Pineapple & Pulled Bacon Pizza - $12 Local Wild Mushroom Pizza - $12 7oz Steak Frites - $20', address:'1055 Canada Pl Building 76, Vancouver, BC, V6C 0C3', phone:'604-235-9827', url:'http://www.thebottleneck.ca/' }, { name:'Tap & Barrel Olympic Village', 
  drinks:'Monday - Friday 2 PM - 6 PM Sunday - Thursday 2 PM - 6 PM & 9 PM - Close Well Highballs (1oz) - $4 Red Truck Lager (16oz) - $4.50 Red Truck Lager (20oz) - $6 BREWHALL Neon Lights Pale Ale (16oz0 - $5 BREWHALL Neon Lights Pale Ale (20oz) - $6.50 Rotating Cider (13oz) - $6 The Hatch Left Bank Blanc (6oz)- $6 The Hatch West Bank Rouge (6oz)- $6', food:'Monday - Friday 2 PM - 6 PM Sunday - Thursday 2 PM - 6 PM & 9 PM - Close Famous Fried Pickles - $6 Gyoza - $8 Handmade Guac & Salsa - $8 Hot Wings - $12 Soft Baked Pretzel - $5 Margherita Pizza - $12 Double Pepperoni Pizza - $12 Pineapple & Pulled Bacon Pizza - $12 Local Wild Mushroom Pizza - $12 7oz Steak Frites - $20', address:'1 Athletes Way, Vancouver, BC, V5Y 0C2', phone:'604-685-2223', url:'http://donnellygroup.ca/the-butcher-bullock' }, { name:'The Bottleneck', 
  drinks:'Tuesday - Thursday 4 PM - 6 PM & 10 PM - 1 AM Friday & Saturday 4 PM - 6 PM & 12 AM - 2 AM Domestic Draught - $4.50 Highballs - $4.50 Glasses of House Wine - $5.50', food:'', address:'870 Granville St, Vancouver, BC, V6Z 1K3', phone:'04-739-4540', url:'http://cambiepubs.com/cambie-gastown/' }, { name:'The Butcher Bullock', 
  drinks:'Monday - Friday 3 PM - 6 PM New York Cocktails - $8 - Paper Plane - Chocolate Lemon - Chocolate Negroni - Green Thumb BC Draught Beer - $5 $6 - Evolve Lake Bench Red, BC, (6oz) - Evolve Lake Bench White, BC, (6oz) - Segura Viudas Brut Reserva. ES', food:'Monday - Friday 3 PM - 6 PM $6 - Yam Falafels - Sausage Roll - Charred Shishito Peppers - Sugar Snap Peas - Beet Hummus & Watermelon Radish - Currywurst', address:'911 W Pender St, Vancouver, BC, V6C 1L6', phone:'604-662-8866', url:'http://www.thecascade.ca/' }, { name:'The Cambie', 
  drinks:'Monday - Sunday 3 PM - 6 PM Caesars - $3.50 High-Balls Well Spirits - $3.50 Draft Beer - $4.50', food:'Monday - Sunday 3 PM - 6 PM $5 - Deep Fried Pickles - Mini Veggie Spring Rolls - Basket Waffle Fries - Classic Poutine - Baked of Pizza Pretzels - Salt & Pepper Dry Ribs', address:'300 Cambie St, Vancouver, BC, V6B 2N3', phone:'604-688-9158', url:'http://emeraldsupperclub.com/' }, { name:'The Casecade Room', 
  drinks:'Monday - Sunday 4 PM - 6 PM Cocktails on Tap - $7 Main St. Beers - $5 House Wine - $5', food:'Monday - Sunday 4 PM - 6 PM Sassy Molassy Burger - $10 Mushroom Poutine - $9 1/2lb Free Range Chicken Wings - $8 Chickpea Fritters - $8 Curry & Chips - $8 Hand Cut Kennebec Chips - $5 Warm Olives - $6 Avocado, Artichoke & Kale Dip - $7 Into The Wild Beef Jerky - $7', address:'2616 Main St, Vancouver, BC, V5T 3E6', phone:'604-709-8650', url:'https://www.thekeeferbar.com/' }, { name:'The Emerald', 
  drinks:'Tuesday - Friday 5 PM - 7 PM Feature Cocktails - $6 Draft Beer - $5 Wine - $5 25% off all Bottles of Wine Half Price Cocktails All Night Tuesday', food:'', address:'555 Gore Ave, Vancouver, BC, V6A 2Z6', phone:'604-559-8477', url:'http://donnellygroup.ca/the-lamplighter/' }, { name:'The Keefer Bar', 
  drinks:'Sunday - Friday 5 PM - 7 PM Select Red, White & Rosé wine - $9 Aperol Spritz - $8 Beer & Cider - $5 Whiskies - $5', food:'Sunday - Friday 5 PM - 7 PM 50% off Bar Snacks, Dim Sum & Dessert *with the purchase of a drink', address:'135 Keefer St, Vancouver, BC, V6A 1X3', phone:'604-688-1961', url:'http://narrowlounge.com/' }, { name:'The Lamplighter Public House', 
  drinks:'Monday - Friday 3PM - 6PM BC Craft Beer - $5 Evolve Lake Bench, White or Red - $5 Segura Viudas Cava - $5 Modern Classic Cocktails - $8', food:'Monday - Friday 3PM - 6PM $5 Specials Sweet Potato Falafels Patatas Bravas Two Rivers Sausage Rolls Charred Shishito Pepper', address:'92 Water St, Vancouver, BC, V6B-2K8', phone:'604-687-4424', url:'https://theparlourrestaurants.com/contact/' }, { name:'The Narrow Lounge', 
  drinks:'Monday - Sunday 5 PM - 7 PM Cocktails (2oz) - $8 Well Drinks (1oz) - $5 Feature Pint (16oz) - $5 Red & White House Wine (6oz)- $5', food:'Monday - Sunday 5 PM - 7 PM Mini Dogs - $2 ea Truffle Popcorn - $5 Small Paprika Popcorn - $5 Potato Wedges - $5 Flat Breads - $10 ea Tacos (fish, chicken & veggie) - $2 ea Nachos - $10 Add free chicken or BBQ pulled pork - $4', address:'1898 Main St, Vancouver, BC, V5T 3B9', phone:'778-737-5206', url:'https://www.thepawnshopyvr.com/' }, { name:'The Parlour', 
  drinks:'Monday - Friday 3 PM - 6 PM Las Perdices - $1 Secret Society Sauvignon Blanc - $1 Monster Rosé - $1 Well Highballs - $5 Tippy Canoe Lager - $5', food:'Monday - Friday 3 PM - 6 PM Olives - $5 Bkh Jerky - $6 Roasted Veg - $10 Brocco - $10 Ahi Carpaccio - $14 Salmon Tartare - $14', address:'1011 Hamilton St, Vancouver, BC, V6B 5T4', phone:'604-568-3322', url:'https://www.glowbalgroup.com/the-roof/index.html' }, { name:'The Pawn Shop', 
  drinks:'Monday - Sunday 3 PM - 6 PM Sunday - Thursday 11 PM - Close $4.95 - House Tequilla (1oz) - House Lager (12.5oz) - Spiked Slush (1oz)', food:'Monday - Sunday 3 PM - 6 PM Sunday - Thursday 11 PM - Close Tacos - $1.49 - Al Pastor - Chicken Tinga - Carnitas - Hongo - Carne Mezclada - Corn & Bean - Chorizo - Squash Sharables - Chips & Salsa - $10.95 - Nachos - $10.95 - Gringo Nachos - $10.95 - Cheese Tots - $9.95 - Infamous Perogies - $11.95 - Chicken Taquitos - $7.95 - Add a Taquito - $1.95 - Wings your way - $11.95 - Chilli Fried - $10.95 - Street Corn Croquettes - $9.95 - Fried Cauliflower & Roasted Yam - $9.95 - Churros - $6.95', address:'1117 Granville St, Vancouver, BC, V6B 2G6', phone:'604-687-7474', url:'https://www.vancouverdine.com/' }, { name:'The Roof', 
  drinks:'Monday - Friday 2:30 PM - 6:00 PM Saturday & Sunday 2:00 PM - 6:00 PM Draft Beers (12oz) - $5 Glass of Wine (5oz) - $5 Raspberry Cosmo (2oz) - $8 Margarita (1oz) - $5 Highballs (1oz) - $5', food:'Monday - Friday 2:30 PM - 6:00 PM Saturday & Sunday 2:00 PM - 6:00 PM Feature Oyster - $1 Crispy Calamari - $9.95 Grilled Corn - $6.95 Hummus - $7.95 Artichoke Dip - $9.95 Phyllo Prawn - $2.95 El Pastor Taco - $3.95 Crisp Bread Fritters - $4.95 Ahi Tuna Poke Stack - $9.95 Wagyu Beef Hot Dog - $8.95 BLT Mac & Cheese Sticks - $7.95 Wagyu Beef Carpaccio - $9.95 Jerk Chicken Hoagie - $3.95', address:'1032 Alberni St 3rd floor, Vancouver, BC, V6E 1A3', phone:'604-637-0777', url:'http://donnellygroup.ca/three-brits/contact/' }, { name:'The Sandbar', 
  drinks:'Monday - Friday 3 PM - 6 PM $5 - Granville Island Pints - Red or White Wine - Sandbar Highball', food:'Monday - Friday 3 PM - 6 PM House Blend Spiced Frites - $4 Bay Shrimp & Avocado Stack - $9 Tacos Frijoles - $8 Avocado Chips - $7 Ahi Tuna Poke Sliders - $9 Chiang Mai Wok Mussels - $10', address:'1535 Johnston St, Vancouver, BC, V6H 3R9', phone:'604-669-9030', url:'http://theunionvancouver.ca/' }, { name:'The Three Brits Public House', 
  drinks:'', food:'Monday - Sunday West Coast Chowder - $10 Buttermilk Chicken - $11 Currywurst - $9 Charred Chicken Salad - $11 Dirty Fries - $8 Crisp Cauliflower - $10 Calamari - $10 Field Greens Salad - $10 Red Chili Wings - $11', address:'1780 Davie St, Vancouver, BC, V6G 1W2', phone:'604-801-6681', url:'http://timbervancouver.com/' }, { name:'The Union', 
  drinks:'Monday - Saturday 5 PM - 6:30 PM & 10 PM - Close Sunday All Day House Red or White Wine (5oz) - $5 House Red or White Wine (8oz) - $8 Draught Beer - $5 House High Balls (1oz) - $4 House High Balls (2oz) - $7 Speciality Cocktails - $8 Rabbit Shooter - $5 Dragon Shooter - $5', food:'', address:'219 Union St, Vancouver, BC, V6A 2B2', phone:'604-568-3230', url:'https://www.tuccraftkitchen.com/contact-2' }, { name:'Timber', 
  drinks:'Monday - Sunday 3 PM - 6 PM Glasses of Red and White Wine - $7 Sleeves of Timber x Main Street Brewing Pilsner - $5', food:'Monday - Sunday 3 PM - 6 PM Soup Of The Day - $2 Smoke Pickled Egg - $1.50 Pepperoni Stick - $2 House Chips - $2 Deep Fried Cheese Curds w/ Jalapeño - $4 Roasted Root vegetables - $4 Bacon Cheddar Twists - $4 Humboldt Calamari - $4 Cauliflower Nettle & Courtenay - $7', address:'1300 Robson St, Vancouver, BC, V6E 1C5', phone:'604-661-2166', url:'http://www.thewinebar.ca/' }, { name:'TUC Craft Kitchen', 
  drinks:'Monday - Sunday 4 PM - 6 PM Wine - $5 Upgrade - $25 All Beer Taps - $5 Aperol Spritz - $7 Brown Derby - $7 Hemingway Daiquiri - $7 Moscow Mule - $7 Blood & Sand - $7 Corpse Reviver No. 2 - $7', food:'Monday - Sunday 4 PM - 6 PM Tempura White Fish & Nahm Jim -$5 Pork Belly Crackling - $4 Crispy Bacon & Egg - $4 Parsnip Fries - $5 Mussels & Sausage - $8 Bread & Other - $5 Pork Croquette & Kimchi - $4 Smashed Potato Fries - $4.5', address:'60 W Cordova St, Vancouver, BC, V6B 1C9', phone:'604-559-8999', url:'https://www.uvavancouver.com/' }, { name:'TWB – The Wine Bar', 
  drinks:'Monday - Sunday 3 PM - 5 PM Montelvini Prosecco (150ml) - $5 Red, White & Rose Wine (150ml) - $5 - $9 Draft Beer (473ml) - $5 - Original 16 Pale Ale - Strange Fellows Talisman Ale - Four Winds Saison - Parallel 49 Gypsy Tears Ruby Ale - Driftwood Brewery Fat Tug IPA - Persephone Nitro Irish Stout - Red Roof Cider', food:'', address:'1167 Marinaside Crescent, Vancouver, BC, V6Z 2Y2', phone:'604-681-4144', url:'http://www.vanfish.com/' }, { name:'Uva Wine & Cocktail Bar', 
  drinks:'Monday - Sunday 2 PM - 5 PM Rum Me Down - $9 Turbulent Skies - $8 A Celery-Ation - $8 Red Racer - $5 Sauvignon Blanc - $6 Merlot / Cabernet Sauvignon) - $6', food:'Monday - Sunday 2 PM - 5 PM Focaccia -$3 Olives - $4 Arancini - $6 Prosciutto e Melone - $12 Burrata - $7 Cheese Plate - $9 Charcuterie Plate- $9', address:'900 Seymour St, Vancouver, BC, V6B 3L9', phone:'604-632-9560', url:'http://www.waterstreetcafe.ca/' }, { name:'Vancouver Fish Company', 
  drinks:'', food:'Monday - Sunday 3 PM - 6 PM Fresh Shucked Oysters - $2 each VFC Superfood Salad - $7 Caesar Salad - $5 Tuna Tataki Tacos - $3 each Halibut Fritters & Fries - $9 Chicken Wings - $7 VFC Maple Walnut Prawns - $9 Mussels - $10 VFC Beef Burger - $7 Smoked Trout Dip - $8', address:'1517 Anderson St, Vancouver, BC, V6H 3R5', phone:'604-559-3474', url:'https://wildebeest.ca/contact' }, { name:'Water Street Café', 
  drinks:'Monday - Sunday 3 PM - 5 PM Eastern Promises Czech Pilsner (15oz) - $5 Peaks & Valleys Pale Ale (15oz) - $5 White Wine (6oz) - $5 (9oz) - $7.50 Red Wine (6oz) - $5 (9oz) - $7.50 Feature Craft Cocktail (2oz) - $8', food:'Monday - Sunday 3 PM - 5 PM Cheese Board - $8 Charcuterie Board - $9 Antipasto Board - $13 Smoked Salmon Plate - $7.25 Bison Carpaccio - $7.50 Hummus & Olives - $5.25 Beet & Arugula Salad - $5.88 Crispy Pork Belly - $7 Calamari Fritti - $6.50 West Coast Crab Cakes - $7.50', address:'300 Water St, Vancouver, BC, V6B 1B6', phone:'604-689-2832', url:'https://wildtale.ca/' }, { name:'Wildebeest', 
  drinks:'Monday - Sunday 5 PM - 6 PM Central City Lager - $5 Parkside Pale Ale - $5 Happy White - $8 Happy Red - $8 Amarocano - $9 Uppercut - $9 Six N’ Change - $9', food:'Monday - Sunday 5 PM - 6 PM Smoked Olives - $4 Skillet Cornbread - $5 Deviled Egg - $3 The Poutine - $9 Bbq Boar Belly - $9 Charcuterie Board - $14 Strait Of Georgia Herring -$13 Bone Marrow - $17 Heirloom Vegetables - $11', address:'120 W Hastings St, Vancouver, BC, V6B 1G8', phone:'604-687-6880', url:'https://www.yewseafood.com/' }, { name:'WildTale', 
  drinks:'', food:'Monday - Sunday 3 PM - 6 PM & 9 PM - Close Braised Meatball - $2.75 ea. BC Salmon Poppers - $6.50 ‘AAA’ Beef Carpaccio - $7.75 Coconut Fried Shrimp - $6.75 Baja Fish Tacos - $6.50 BBQ’d Chicken Wings - $6.75 P.E.I. Lobster Roll - $5.75 ea (min 2) Parmesan Fries - $6.25 Sesame Crusted Albacore - $8.25 Fresh Seafood Ceviche - $7.25 Hawaiian Tuna Poke - $8.25 Grilled Oysters - $3.25 ea. Buttermilk Fried Oysters - $3.25 ea. Clams - $9.50 Mussels - $10.75 Clams & Mussels - $11.75', address:'1079 Mainland St, Vancouver, BC, V6B 5P9', phone:'604-428-9211', url:'' }, { name:'YEW Seafood + Bar', 
  drinks:'Monday - Sunday 2:00 PM - 6:00 PM Signature Cocktails - $15', food:'', address:'791 W Georgia St, Vancouver, BC, V6C 2T4', phone:'604-692-4939', url:'' }
]